### ISSUE TITLE
confluence-crack

### ISSUE THREAD

**Issue by Axxxolotl** [guywiththecrack/jira-crack#7]
Hello! Great thanks, it works with jira 9.6.0
But does it works with confluence? and which version?

**Comment by Axxxolotl** [comment]
I tryed it with atlassian-confluence-7.20.0-x64.bin but it doesn't work

**Comment by guywiththecrack** [comment]
@Axxxolotl 
hey there, some people told me that it worked for them , the code or the other repository which has some jar files that can give you the code, but i haven't tried them .
