### ISSUE TITLE
Plugin Marketplace

### ISSUE THREAD

**Issue by maurodouglas** [guywiththecrack/jira-crack#8]
Hey man, there's a way to also crack the plugins present in the Atlassian Marketplace, I already tried to use the plugin atlassian-universal-plugin-manager-plugin-4.0.4.jar, but it didn't work on the newer versions.

**Comment by guywiththecrack** [comment]
hey there, some people told me that it worked for them and they used it for the plugins, but i haven't tried it  ,there is  the code or the other repository which has some jar files that can give you the code, but i haven't tried them .

**Comment by guywiththecrack** [comment]
> Hey man, there's a way to also crack the plugins present in the Atlassian Marketplace, I already tried to use the plugin atlassian-universal-plugin-manager-plugin-4.0.4.jar, but it didn't work on the newer versions.
